DecoratorDesign/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('',include('firm.urls',namespace='firm')),
    url('shop/', include('shop.urls', namespace='shop')),
    url('blog/',include('blog.urls',namespace='blog')),
    url('project/',include('furnitureapp.urls',namespace='furnitureapp')),
]

blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from .views import *
# 全文搜索
from haystack.views import SearchView


app_name = 'blog'

urlpatterns = [
    url(r'^register/$', register, name='register'),
    url(r'^$', login, name='login'),
    url(r'^public/$', public, name='public'),
    url(r'^total/$', total, name='total'),
    url(r'^single/(\d+)/$', single, name='single'),
    url(r'^see/$', see, name='see'),
    url(r'^large_total/$', large_total, name='large_total'),
    # 全文搜索，调用第三方库中的视图函数
    url(r'^search/$', SearchView(), name='search'),

]

firm/urls.py
from django.conf.urls import url
from . import views

app_name = 'firm'


urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^pricing/$',views.pricing,name='pricing'),
    url(r'^question/$', views.faqs,name='question'),
    url(r'^team-single/(\d+)/$',views.team_single,name='team-single'),
    url(r'^team/$',views.team,name='team'),
    url(r'^about/$',views.about,name='about'),
]

blog/models.py
from django.db import models
from tinymce.models import HTMLField

# Create your models here.


class Type(models.Model):
    """文章分类"""
    tName = models.CharField(max_length=20, default='纹理会话')

    def __str__(self):
        return self.tName


class Tag(models.Model):
    """文章标签"""
    tName = models.CharField(max_length=20, default='家具')

    def __str__(self):
        return self.tName


class UserSell(models.Model):
    """用户类"""
    # todo 添加图片继承form
    uheaderImg = models.ImageField(upload_to='userHeaders')
    uName = models.CharField(max_length=20, default='bh')
    uPwd = models.CharField(max_length=10, default='000')
    uType = models.CharField(max_length=10, default='sell')
    # 简介
    uBrief = models.CharField(max_length=50)


class Article(models.Model):
    """文章"""
    aAuthor = models.ForeignKey(UserSell, on_delete=models.CASCADE)
    aTitle = models.CharField(max_length=20)
    aPublicTime = models.DateTimeField(auto_now=True)
    aContent = HTMLField()
    aType = models.ForeignKey(Type, on_delete=models.CASCADE)
    # 多对多
    aTag = models.ManyToManyField(Tag)
    aBackgroundImage = models.ImageField(upload_to='articleImages')
    aReadNum = models.SmallIntegerField(default='0')


class Comment(models.Model):
    """评论"""
    cPublicPeople = models.CharField(max_length=20)
    cEmail = models.EmailField()
    cPhone = models.CharField(max_length=11)
    cUrl = models.URLField()
    cContent = models.CharField(max_length=500)
    cArticle = models.ForeignKey(Article, on_delete=models.CASCADE)
    # cComtent = models.ForeignKey('self', on_delete=models.CASCADE)

blog/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect,reverse
from .models import *
from django.core.paginator import Paginator


def register(request):
    """注册"""
    if request.method == 'POST':
        name = request.POST['name']
        pwd = request.POST['pwd']
        jj = request.POST['jj']
        headerimage = request.FILES['headerimage']
        UserSell.objects.create(uName=name, uheaderImg=headerimage, uPwd=pwd, uBrief=jj)
        return redirect(reverse('blog:login'))
    return render(request, 'blog/register.html')


def login(request):
    """login"""
    if request.method == 'POST':
        name = request.POST['name']
        pwd = request.POST['pwd']
        us = UserSell.objects.filter(uName=name, uPwd=pwd)
        if len(us) > 0:
            # 设置session
            request.session['u'] = us[0].id
            return redirect(reverse('blog:public'))
    return render(request, 'blog/login.html')


def public(request):
    """发表文章"""
    if request.method == 'POST':
        title = request.POST['title']
        content = request.POST['content']
        type = Type.objects.get(pk=request.POST['type'])
        tags = request.POST['tags']
        img = request.FILES['articleImage']

        ari = Article()
        ari.aBackgroundImage = img
        ari.aTitle = title
        ari.aContent = content
        ari.aType = type
        ari.aAuthor = UserSell.objects.get(pk=int(request.session['u']))
        ari.save()
        for t in tags:
            ari.aTag.add(int(t))
        ari.save()
    # 查询分类，传入内容
    types = Type.objects.all()
    tags = Tag.objects.all()
    para = {
        'types': types,
        'tags': tags,
    }
    return render(request, 'blog/public_article.html', para)


def search_resource():
    """
    查询共有资源
    :return: {'articles': types,
        'tags': tags,
        'types': articles,}
    """
    types = Type.objects.all()
    tags = Tag.objects.all()
    articles = Article.objects.all()
    # 归档
    t_set = set()
    for a in articles:
        time = a.aPublicTime.month
        t_set.add('2019-'+str(time))
    # i = 1
    # for m in t_set:
    #     if i < 5:
    #         a = []
    #         a.append('2019-'+str(m))


    # 热门文章
    hot_arls = articles.order_by('-aReadNum')[:3]
    para = {
        'articles': articles,
        'tags': tags,
        'types': types,
        'hot_arls': hot_arls,
        'guidang': t_set,
    }
    return para


def total(request):
    """
    总览页
    :param request:
    :return:
    """
    para = search_resource()
    pindex = request.GET.get('page')
    if pindex is None:
        pindex = 1
    p = Paginator(para['articles'], 6)
    pindex = int(pindex)
    page = p.page(pindex)
    para['articles'] = page.object_list
    para['page'] = page
    para['p'] = p
    return render(request, 'blog/blog.html', para)


def single(request, aid):
    """
    详情页
    :param request:
    :param aid:书的id
    :return:
    """
    arl = Article.objects.get(pk=int(aid))
    # 阅读数加一
    arl.aReadNum += 1
    arl.save()
    coms = arl.comment_set.all()
    para = search_resource()
    para['arl'] = arl
    para['coms'] = coms
    print('.....................................', para)
    return render(request, 'blog/blog-single.html', para)


def see(request):
    part_types = None
    type = request.GET.get('type')
    # 对应类型id
    value = request.GET.get('value')
    if type == 'type':
        part_types = Type.objects.get(pk=int(value)).article_set.all()
    elif type == 'tag':
        part_types = Tag.objects.get(pk=int(value)).article_set.all()
    elif type== 'date':
        year = value[:4]
        month = value[5:]
        part_types = Article.objects.filter(aPublicTime__year=year, aPublicTime__month=month).all()
    para = search_resource()

    p = Paginator(part_types, 6)
    pindex = request.GET.get('page')
    if pindex is None:
        pindex = 1
    pindex = int(pindex)
    page = p.page(pindex)
    para['articles'] = page.object_list
    para['page'] = page
    para['type'] = type
    para['value'] = value
    para['p'] = p
    return render(request, 'blog/blog.html', para)


def large_total(request):
    para = search_resource()
    return render(request, 'blog/blog-large-image.html', para)

templates/blog/blog-single.html
{% extends 'blog/base_blog.html' %}

{% block title %}
详情
{% endblock %}


{% block stylesheel %}

{% endblock %}


{% block right %}
<section class="page-title" style="background-image: url('/static/images/background/bg-page-title-1.jpg')">
        <div class="auto-container">
            <h1>Blog Single Post</h1>
        </div>
    </section>

    <!--Page Info-->
    <section class="page-info">
        <div class="auto-container clearfix">
            <div class="pull-left"><h2>Blog Single Post</h2></div>
            <div class="pull-right">
                <ul class="bread-crumb clearfix">
                    <li><a href="{% url 'firm:index' %}">Home</a></li>
                    <li><a href="{% url 'blog:total' %}">Blog</a></li>
                    <li>Blog Single Post</li>
                </ul>
            </div>
        </div>
    </section>

{% endblock %}

{% block leftcontent %}
<!--Content Side-->
    <div class="content-side col-lg-9 col-md-8 col-sm-12 col-xs-12">

        <!--News Section-->
        <section class="news-section large-image-view blog-details no-padd-top no-padd-bottom">
            <!--News Style One / Boxed-->
            {% if arl %}
                <div class="news-style-one boxed">
                <div class="inner-box">
                    <figure class="image-box"><img src="/static/media/{{ arl.aBackgroundImage }}" alt=""></figure>
                    <div class="content">
                        <h3><a >{{ arl.aTitle }}</a></h3>
                        <ul class="post-meta clearfix">
                            <li><a href="#"><span class="icon fa fa-clock-o"></span> {{ arl.aPublicTime }}</a></li>
                            <li><a href="{% url 'blog:see' %}?type=type&value={{ arl.aType.id }}"><span class="icon fa fa-tags"></span> {{ arl.aType }}</a></li>
                            <li><a href="#"><span class="icon fa fa-eye"></span> {{ arl.aReadNum }} Views</a></li>
{#                            <li><a href="#"><span class="icon fa fa-comments"></span> {{ coms.count }}</a></li>#}
                        </ul>
                        <div class="text">
{#                            <p>Explain to you how all this mistaken idea of denouncing pleasures sed nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. and praising pain was born and I will give the actual teachings.</p>#}
{#                            <blockquote>Michel ivauedaus rutrum mi utercture aliquamhabitasse platore dictumst. Integer sagittis vulputate  similique sunt in culpa qui officia deserunt.</blockquote>#}
{#                            <p>We denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charm of pleasure of the moment, so blinded by desire, that they cannot foresee the pain ut and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying uts through shrinking from toil and pain  These cases are perfectly simple and easy to distinguish. </p>#}
                            {{ arl.aContent|safe }}
                        </div>
                        <div class="post-bottom clearfix">

                            <ul class="share-options pull-left clearfix">
                                <li><strong>Did You Like This Post? Share it :</strong></li>
                                <li><a href="#"><span class="fa fa-facebook-f"></span></a></li>
                                <li><a href="#"><span class="fa fa-twitter"></span></a></li>
                                <li><a href="#"><span class="fa fa-google-plus"></span></a></li>
                                <li><a href="#"><span class="fa fa-linkedin"></span></a></li>
                                <li><a href="#"><span class="fa fa-skype"></span></a></li>
                            </ul>

                            <ul class="post-controls pull-right clearfix">
{#                                {% if arl.id != articles.all.first.id %}#}
{#                                    <li><a href="{% url 'blog:single' arl.id|add:-1 %}" class="prev-post"><span class="fa fa-angle-left"></span> &nbsp; Prev</a></li>#}
{#                                {% endif %}#}
{#                            {% if arl.id == articles.all.last.id %}#}
{#                                <li><a href="{% url 'blog:single' arl.id|add:1 %}" class="next-post">Next &nbsp; <span class="fa fa-angle-right"></span></a></li>#}
{#                            {% endif %}#}
                                </ul>

                        </div>
                    </div>
                </div>
            </div>
            {% endif %}




            <div class="sec-title medium"><h2>About Author</h2></div>

            <!--About Author-->
            <div class="post-author">
                <div class="inner-box">
                    <figure class="author-thumb"><img style="height: 100px;width: 100px;" src="/static/media/{{ arl.aAuthor.uheaderImg }}" alt=""></figure>
                    <h4>{{ arl.aAuthor.uName }}<span class="author-designation">( Author)</span></h4>
                    <div class="text">{{ arl.aAuthor.uBrief }} </div>
                </div>
            </div>
            {% if coms %}
                <div class="sec-title medium"><h2>Comments ({{ coms.count }})</h2></div>

            <!--Comments Area-->
            <div class="comments-area">

                <div class="comment-box">

                    <div class="comment">
                        <div class="comment-inner">
                            <div class="author-thumb">
{#                                <img src="images/resource/author-thumb-5.jpg" alt="">#}
                            </div>
                            <div class="comment-header clearfix">
                                <h4>{{ coms }}</h4>
                                <div class="comment-info">17 August 2015 at 12.00pm / <a href="#">Reply</a></div>
                            </div>
                            <div class="text">Culpa qui officia deserunt mollitia animin id est laborum et seds dolorum seds fuga. uni harum quidem rerum facilis est et expedita ut distinctio. Nam sed libero tempore, cum soluta nobis seds est eligendi optio cumque nihil impedit quo repellendus eligendi optio cumque.</div>
                        </div>
                    </div>

                    <div class="comment reply-comment">
                        <div class="comment-inner">
                            <div class="author-thumb"><img src="images/resource/author-thumb-6.jpg" alt=""></div>
                            <div class="comment-header clearfix">
                                <h4>Vital Meckey</h4>
                                <div class="comment-info">21 December 2015 at 11.00am / <a href="#">Reply</a></div>
                            </div>
                            <div class="text">Idea of denouncing pleasure and praising pains was borns and I will gives you a complete account of the system, and expound the actual teachings of the great seds ut labo explorer of the sed truth, the master-builder of human happiness.</div>
                        </div>
                    </div>

                </div>
            </div>

            <div class="sec-title medium"><h2>Leave a Reply</h2></div>

            <div class="comment-form">
                        	<!--form-box-->
                            <div class="form-box default-form">
                                <div class="contact-form default-form">
                                    <form method="post" action="contact.html">
                                        <div class="row clearfix">

                                            <div class="form-group col-md-6 col-sm-6 col-xs-12">
                                                <input type="text" name="username" value="" placeholder="Your Name ">
                                            </div>

                                            <div class="form-group col-md-6 col-sm-6 col-xs-12">
                                                <input type="email" name="email" value="" placeholder="Email Address " required>
                                            </div>

                                            <div class="form-group col-md-6 col-sm-6 col-xs-12">
                                                <input type="text" name="number" value="" placeholder="Phone">
                                            </div>

                                            <div class="form-group col-md-6 col-sm-6 col-xs-12">
                                                <input type="text" name="website" value="" placeholder="Website">
                                            </div>

                                            <div class="form-group col-md-12 col-sm-12 col-xs-12">
                                                <textarea name="message" placeholder="Comments "></textarea>
                                            </div>
                                            <div class="form-group col-md-12 col-sm-12 col-xs-12">
                                                <button type="submit" class="theme-btn btn-style-two">Post Comment</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
            {% endif %}


        </section>

    </div><!--End Content Side-->

{% endblock %}

templates/blog/blog.html
{% extends 'blog/base_blog.html' %}
{% block title %}
博客
{% endblock %}


{% block stylesheel %}

{% endblock %}


{% block right %}
<section class="page-title" style="background-image: url('/static/images/background/bg-page-title-1.jpg')">
        <div class="auto-container">
            <h1>Blog Standard</h1>
        </div>
    </section>

    <!--Page Info-->
    <section class="page-info">
        <div class="auto-container clearfix">
            <div class="pull-left"><h2>Blog Standard</h2></div>
            <div class="pull-right">
                <ul class="bread-crumb clearfix">
                    <li><a href="{% url 'firm:index' %}">Home</a></li>
                    <li><a href="{% url 'blog:total' %}">Blog</a></li>
                    <li>Blog Standard</li>
                </ul>
            </div>
        </div>
    </section>

{% endblock %}

{% block leftcontent %}
<div class="content-side col-lg-9 col-md-8 col-sm-12 col-xs-12">

                    <!--News Section-->
                    <section class="news-section list-view no-padd-top no-padd-bottom">

                        <!--News Style One-->

                        {% for a in articles %}
                            <div class="news-style-one">
                                <div class="inner-box">
                                    <div class="row clearfix">

                                        <div class="image-column col-md-5 col-sm-6 col-xs-12">
                                            <figure class="image-box"><img style="height: 250px;width: 370px;" src="/static/media/{{ a.aBackgroundImage }}" alt="文章配图"><a class="overlay-link" href="{% url 'blog:single' a.id %}"><span class="icon flaticon-plus-1"></span></a></figure>
                                        </div>
                                        <div class="content-column col-md-7 col-sm-6 col-xs-12">
                                            <div class="content">
                                                <h3><a href="{% url 'blog:single' a.id %}"> {{ a.aTitle }}</a></h3>
                                                <ul class="post-meta clearfix">
                                                    <li><a><span class="icon fa fa-clock-o"></span> {{ a.aPublicTime }}</a></li>
                                                    <li><a href="{% url 'blog:see' %}?type=type&value={{ a.aType.id }}"><span class="icon fa fa-tags"></span> {{ a.aType }}</a></li>
                                                    <li><a><span class="icon fa fa-eye"></span> {{ a.aReadNum }}</a></li>
{#                                                    <li><a><span class="icon fa fa-comments"></span></a></li>#}
                                                </ul>
                                                <div class="text">{{ a.aContent|slice:100 }} </div>
                                                <br>
                                                    <div class="author-info">
                                                        <figure class="author-thumb"><img style="width: 50px;height: 50px;" src="/static/media/{{ a.aAuthor.uheaderImg }}" alt="作者图"></figure>
                                                        <h4>{{ a.aAuthor.uName }}</h4>
                                                        <div class="designation">Team Leader</div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                </div>
                             </div>
                        {% endfor %}





                        <!-- Styled Pagination -->
                        <div class="styled-pagination padd-top-20 text-left">
                            <ul>
{#                                <li><a class="prev" href="#"><span class="fa fa-angle-left"></span></a></li>#}
                                {% if type %}
                                    <li><a href="?page=1&type={{ type }}&value={{ value }}" >首页</a></li>
                                {% else %}
                                    <li><a href="?page=1" >首页</a></li>
                                {% endif %}


                                {% if page.has_previous %}
                                    {% if type %}
                                        <li><a href="?page={{ page.number|add:-1 }}&type={{ type }}&value={{ value }}" >{{ page.number|add:-1 }}</a></li>
                                    {% else %}
                                        <li><a href="?page={{ page.number|add:-1 }}" >{{ page.number|add:-1 }}</a></li>
                                    {% endif %}
                                {% endif %}

                                {% if type %}
                                    <li><a href="?page={{ page.number }}&type={{ type }}&value={{ value }}" class="active">{{ page.number }}</a></li>
                                {% else %}
                                    <li><a href="?page={{ page.number }}" class="active">{{ page.number }}</a></li>
                                {% endif %}


                                {% if page.has_next %}
                                    {% if type %}
                                        <li><a href="?page={{ page.number|add:1 }}&type={{ type }}&value={{ value }}">{{ page.number|add:1 }}</a></li>
                                    {% else %}
                                        <li><a href="?page={{ page.number|add:1 }}">{{ page.number|add:1 }}</a></li>
                                    {% endif %}
                                {% endif %}
                                {% if type %}
                                        <li><a href="?page={{ p.num_pages }}&type={{ type }}&value={{ value }}">尾页</a></li>
                                    {% else %}
                                        <li><a href="?page={{ p.num_pages }}">尾页</a></li>
                                {% endif %}
                                </ul>
                        </div>

                    </section>

                </div><!--End Content Side-->

{% endblock %}

templates/blog/login.html
{% extends 'blog/base_index.html' %}


{% block title %}
login
{% endblock %}
form{
    text-align: center;
}

{% block stylesheel %}
{% endblock %}


{% block blog %}
    <div style="width: 1000px; margin: 200px auto">
        <form action="#" method="post" class="form-horizontal">
            {% csrf_token %}
            请输入您的账户：<input type="text" name="name" class="text form-control">
            <br>
            请输入您的密码：<input type="password" name="pwd" class="form-control " id="inputPassword3">
            <br>
            <input type="submit" value="提交" class="btn ">
        </form>
        <br>还没有账号？<a href="{% url 'blog:register' %}">注册</a>
    </div>
{% endblock %}

templates/blog/public_article.html
{% extends 'blog/base_blog.html' %}


{% block title %}
发表
{% endblock %}


{% block stylesheel %}
    <script src="/static/tiny_mce/tiny_mce.js"></script>
    <script>
    tinyMCE.init({
        'mode': 'textareas',
        'theme': 'advanced',
        'width':800,
        'height': 500,
    })
    </script>
{% endblock %}


{% block blog %}
    <div style="width: 1000px; margin: 200px auto">
        <form action="{% url 'blog:public' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <big>
                请输入您的题目：<input class="text form-control" style="height: 30px;" type="text" name="title">
            <br>
            请输入您的内容：<textarea class="text  form-control" style="height: 30px;" name="content" ></textarea>
            请上传您的图片：<input type="file" name="articleImage">
            <br>
            请选择您的分类：
            {% for t in types %}
                <input type="radio" name="type" value="{{ t.id }}"
                 class="radio radio-inline " style="width: 15px;">{{ t.tName }}
            {% empty %}
                可以不选
            {% endfor %}
            <br>
            请选择您的标签：
            {% for tag in tags %}
                <input class="checkbox checkbox-inline" style="width: 15px;height: 80px;" type="checkbox" name="tags" value="{{ tag.id }}">{{ tag.tName }}
            {% empty %}
                可以不选
            {% endfor %}
            <br>
            <input type="submit" class="btn btn-lg" value="提交">
            </big>

        </form>
    </div>

{% endblock %}

templates/blog/register.html
{% extends 'blog/base_index.html' %}


{% block title %}
register
{% endblock %}


{% block stylesheel %}
{% endblock %}


{% block blog %}
    <div style="width: 1000px; margin: 200px auto">
        <form action="{% url 'blog:register' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            请输入您的账户：<input type="text" name="name" class="form-control">
            <br>
            请输入您的密码：<input type="password" name="pwd" class="form-control">
            <br>
            请输入您的简介：<input type="text" name="jj" class="form-control">
            <br>
            请上传您的头像：<input type="file" name="headerimage">
            <br>
            <input type="submit" value="提交" class="btn button">
        </form>
    </div>
{% endblock %}