DecoratorDesign/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('',include('firm.urls',namespace='firm')),
    url('shop/', include('shop.urls', namespace='shop')),
    url('blog/',include('blog.urls',namespace='blog')),
    url('project/',include('furnitureapp.urls',namespace='furnitureapp')),
]

blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from .views import *
# 全文搜索
from haystack.views import SearchView


app_name = 'blog'

urlpatterns = [
    url(r'^register/$', register, name='register'),
    url(r'^$', login, name='login'),
    url(r'^public/$', public, name='public'),
    url(r'^total/$', total, name='total'),
    url(r'^single/(\d+)/$', single, name='single'),
    url(r'^see/$', see, name='see'),
    url(r'^large_total/$', large_total, name='large_total'),
    # 全文搜索，调用第三方库中的视图函数
    url(r'^search/$', SearchView(), name='search'),

]

firm/urls.py
from django.conf.urls import url
from . import views

app_name = 'firm'


urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^pricing/$',views.pricing,name='pricing'),
    url(r'^question/$', views.faqs,name='question'),
    url(r'^team-single/(\d+)/$',views.team_single,name='team-single'),
    url(r'^team/$',views.team,name='team'),
    url(r'^about/$',views.about,name='about'),
]

shop/urls.py
from django.conf.urls import url
from . import views

app_name = 'shop'
urlpatterns = [
    url(r'^shop/$', views.shop, name='shop'),
    url(r'^shop_single/(\d+)/$', views.shop_single, name='shop_single'),
    url(r'^shopping_cart/$', views.shopping_cart, name='shopping_cart'),
    url(r'^login/$', views.login, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^checkout/$', views.checkout, name='checkout'),
    url(r'^category/(\d+)/$', views.category, name='category'),
    url(r'^tag/(\d+)/$', views.tag, name='tag'),
    url(r'^add_cart/(\d+)/$', views.add_cart, name='add_cart'),
    url(r'^price_filter/$', views.price_filter, name='price_filter'),
    url(r'^review/(\d+)/$', views.review, name='review'),
    url(r'^remove_product/(\d+)/$', views.remove_product, name='remove_product'),
    url(r'^search/$', views.search, name='search'),
]

shop/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


# Create your models here.


class User(models.Model):
    name = models.CharField(max_length=20, unique=True)
    email = models.EmailField()
    pwd = models.CharField(max_length=20)
    image = models.ImageField(upload_to='users', default='users/author-thumb-2.jpg')

    def __str__(self):
        return self.name


class Product(models.Model):
    """ 商品 """
    name = models.CharField(max_length=50)
    star = models.IntegerField(validators=[MaxValueValidator(5), MinValueValidator(0)], default=5)
    price = models.FloatField()
    image = models.ImageField(upload_to='products')
    remains = models.IntegerField(default=100)
    describe = models.TextField()
    pub_date = models.DateField(auto_now_add=True)
    category = models.ForeignKey(to='Category', on_delete=None)
    tag = models.ForeignKey(to='Tag', on_delete=None)

    def __str__(self):
        return self.name


class Cart(models.Model):
    """ 购物车 """
    user = models.ForeignKey(to='User', on_delete=None)
    product = models.ForeignKey(to='Product', on_delete=None)
    quantity = models.PositiveIntegerField(default=1)


class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Review(models.Model):
    content = models.TextField()
    stars = models.FloatField()
    user = models.ForeignKey(to='User', on_delete=None)
    product = models.ForeignKey(to='Product', on_delete=None)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.content

shop/views.py
from django.shortcuts import render, redirect, reverse
from . import models
from django.core.paginator import Paginator, PageNotAnInteger, InvalidPage
from django.http import HttpResponse
# Create your views here.


def render_shop(request, products):
    """ 给定产品信息，渲染shop页面 """
    categories = models.Category.objects.all()
    tags = models.Tag.objects.all()
    latest_products = models.Product.objects.all().order_by('pub_date')[0:3]

    # 根据产品数量分页
    limit = 9  # 按每页9条分页
    page_number = 3  # 每页页码数量
    paginator = Paginator(products, limit)
    page_range = None
    if request.method == "GET":
        # 获取 url 后面的 page 参数的值, 首页不显示 page 参数, 默认值是 1
        page = request.GET.get('page')
        try:
            products = paginator.page(page)
        # 注意捕获异常
        except PageNotAnInteger:
            # 如果请求的页数不是整数, 返回第一页。
            products = paginator.page(1)
        except InvalidPage:
            # 如果请求的页数不存在, 重定向页面
            return HttpResponse('找不到页面的内容')
        finally:
            # 生成当前页页码范围
            if products.number + page_number < products.paginator.num_pages:
                page_range = range(products.number, products.number + page_number)
            else:
                page_range = range(products.number, products.paginator.num_pages)
    print(page_range)
    return render(request, 'shop/shop.html',
                  {'products': products,
                   'categories': categories,
                   'tags': tags,
                   'latest_products': latest_products,
                   'page_range': page_range,
                   })


def shop(request):
    """ 商品页面 """
    products = models.Product.objects.all()
    return render_shop(request, products)


def shop_single(request, product_id):
    """ 商品详情 """
    product = models.Product.objects.get(pk=product_id)
    categories = models.Category.objects.all()
    tags = models.Tag.objects.all()
    latest_products = models.Product.objects.all().order_by('pub_date')[0:3]
    return render(request, 'shop/shop-single.html',
                  {'product': product, 'categories': categories, 'tags': tags, 'latest_products': latest_products})


def shopping_cart(request):
    """ 购物车 """
    user = models.User.objects.get(name=request.session.get('username'))
    cart = user.cart_set.all()

    total_price = 0
    for product in cart:
        total_price += product.product.price * product.quantity

    return render(request, 'shop/shopping-cart.html', {'cart': cart, 'total_price': total_price})


def login(request):
    """ 登录 """
    username = request.POST.get('username')
    pwd = request.POST.get('pwd')
    user = models.User.objects.filter(name=username, pwd=pwd).first()
    if user:
        request.session['username'] = username
        return redirect(to=reverse('shop:shop'))
    else:
        return render(request, 'shop/register.html', {'failed': True})


def register(request):
    """ 注册 """
    if request.method == 'GET':
        return render(request, 'shop/register.html')
    elif request.method == 'POST':
        username = request.POST.get('username')
        pwd = request.POST.get('pwd')
        email = request.POST.get('email')
        models.User.objects.create(name=username, pwd=pwd, email=email)
        return redirect(to=reverse('shop:register'))


def checkout(request):
    """ 支付 """
    if request.method == 'POST':
        # TODO 第三方支付
        return redirect(to=reverse('shop:shop'))
    return render(request, 'shop/checkout.html')


def add_cart(request, product_id):
    """ 添加商品到购物车 """
    product = models.Product.objects.get(pk=product_id)
    user = models.User.objects.get(name=request.session.get('username'))

    try:
        quantity = request.POST.get('quantity')
    except Exception as e:
        models.Cart.objects.create(product=product, user=user)
    else:
        models.Cart.objects.create(product=product, user=user, quantity=quantity)

    return redirect(to=reverse('shop:shopping_cart'))


def remove_product(request, product_id):
    """ 删除购物车中的商品 """
    user = models.User.objects.get(name=request.session.get('username'))
    product = models.Product.objects.get(pk=product_id)
    user.cart_set.filter(product=product).filter().first().delete()
    return redirect(to=reverse('shop:shopping_cart'))


def category(request, category_id):
    """ 分类展示商品 """
    category_ = models.Category.objects.get(pk=category_id)
    products = category_.product_set.all()
    return render_shop(request, products)


def tag(request, tag_id):
    """ 由标签展示商品 """
    tag_ = models.Tag.objects.get(pk=tag_id)
    products = tag_.product_set.all()
    return render_shop(request, products)


def price_filter(request):
    """ 由价格过滤商品 """
    minvalue = request.POST.get('minvalue')
    maxvalue = request.POST.get('maxvalue')
    products = models.Product.objects.filter(price__gte=minvalue, price__lte=maxvalue)
    print(products, maxvalue, minvalue)
    return render_shop(request, products)


def review(request, product_id):
    username = request.session.get('username')
    user = models.User.objects.get(name=username)
    product = models.Product.objects.get(pk=product_id)
    # 计算商品小星星
    stars = int(request.POST.get('stars'))
    score = product.star * product.review_set.count()
    product.star = (score + stars) / (product.review_set.count() + 1)

    content = request.POST.get('content')
    models.Review.objects.create(content=content, user=user, product=product, stars=stars)
    return redirect(to=reverse('shop:shop_single', args=product_id))


def search(request):
    product_name = request.POST.get('product_name')
    products = models.Product.objects.filter(name__contains=product_name)
    return render_shop(request, products)

templates/shop/shop-single.html
{% extends 'shop/shop.html' %}

{% block title %}
    详情页
{% endblock %}

   
{% block body %}

    <!--Page Title-->
    <section class="page-title" style="background-image:url(/static/images/background/bg-page-title-1.jpg);">
        <div class="auto-container">
            <h1>Single Shop</h1>
        </div>
    </section>

    <!--Page Info-->
    <section class="page-info">
        <div class="auto-container clearfix">
            <div class="pull-left"><h2>Single Shop</h2></div>
            <div class="pull-right">
                <ul class="bread-crumb clearfix">
                    <li><a href="{% url 'firm:index' %}">Home</a></li>
                    <li><a href="{% url 'shop:shop' %}">Shop</a></li>
                    <li>Single Shop</li>
                </ul>
            </div>
        </div>
    </section>


    <!--Sidebar Page-->
    <div class="sidebar-page-container">
        <div class="auto-container">
            <div class="row clearfix">

                <!--Content Side-->
                <div class="content-side col-lg-9 col-md-8 col-sm-12 col-xs-12">

                    <!--Product Details Section-->
                    <section class="products-section product-details no-padd-top no-padd-bottom">
                        <!--Basic Details-->
                        <div class="basic-details">
                            <div class="row clearfix">
                                <div class="image-column col-md-5 col-sm-6 col-xs-12">
                                    <figure class="image-box"><img class="img-responsive" src="/static/media/{{ product.image }}" alt=""></figure>
                                </div>
                                <div class="info-column col-md-7 col-sm-6 col-xs-12">
                                    <div class="details-header">
                                        <h4>{{ product.name }} </h4>
                                        <div class="rating"><span class="fa fa-star"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span> <span class="txt">({{ product.review_set.count }} Reviews)</span></div>
                                        <div class="item-price">$ {{ product.price }}</div>

                                    </div>

                                    <div class="text">
                                        <p>{{ product.describe }}</p>
                                    </div>

                                    <div class="clearfix options">
                                        <form action="{% url 'shop:add_cart' product.id %}"></form>
                                        <div class="pull-left padd-right-20"><a href="{% url 'shop:shopping_cart' %}" class="theme-btn btn-style-one">Add to Cart</a></div>
                                    </div>

                                </div>
                            </div>
                        </div><!--Basic Details-->

                        <!--Product Info Tabs-->
                        <div class="product-info-tabs">

                            <!--Product Tabs-->
                            <div class="prod-tabs" id="product-tabs">

                                <!--Tab Btns-->
                                <div class="tab-btns clearfix">
                                    <a href="#" class="tab-btn active-btn">Reviews ( {{ product.review_set.count }} )</a>
                                </div>

                                <!--Tabs Container-->
                                <div class="tabs-container">

                                    <!--Tab / Active Tab-->
                                    <div class="tab active-tab" id="prod-reviews">

                                        <!--Reviews Container-->
                                        <div class="reviews-container">

                                            {% for review in product.review_set.all %}
                                            <!--Reviews-->
                                            <article class="review-box clearfix">
                                                <figure class="rev-thumb"><img src="/static/media/{{ review.user.image }}" alt=""></figure>
                                                <div class="rev-content">
                                                    <div class="rev-header clearfix">
                                                    	<h4>{{ review.user.name }}</h4>
                                                        <div class="rating"><span class="fa fa-star"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span></div>
                                                    </div>
                                                    <div class="rev-info">{{ review.date }}</div>
                                                    <div class="rev-text">{{ review.content }}</div>
                                                </div>
                                            </article>
                                            {% endfor %}

                                        </div>

                                        <!--Add Review-->
                                        <div class="add-review">
                                            <div class="sec-title medium"><h2>Add Review</h2></div>

                                            <form method="post" action="{% url 'shop:review' product.id %}">
                                                {% csrf_token %}
                                            	<div class="row clearfix">
                                                    <div class="form-group col-md-12 col-sm-12 col-xs-12">
                                                        <label>Your Rating </label>

                                                        <ul class="rating">
                                                            <input class="quantity-spinner form-control" type="text" value="1" name="stars">
{#                                                            <li><a href="#" class="rate-box" title="2 Out of 5"><span class="fa fa-star"></span> <span class="fa fa-star"></span></a></li>#}
{#                                                            <li><a href="#" class="rate-box" title="3 Out of 5"><span class="fa fa-star"></span> <span class="fa fa-star"> </span> <span class="fa fa-star"></span></a></li>#}
{#                                                            <li><a href="#" class="rate-box" title="4 Out of 5"><span class="fa fa-star"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span></a></li>#}
{#                                                            <li><a href="#" class="rate-box" title="5 Out of 5"><span class="fa fa-star"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span></a></li>#}
                                                        </ul>
                                                    </div>
                                                    <div class="form-group col-md-12 col-sm-12 col-xs-12">
                                                        <textarea name="content" placeholder="Review Comments"></textarea>
                                                    </div>
                                                    <div class="form-group col-md-12 col-sm-12 col-xs-12">
                                                        <button type="submit" class="theme-btn hvr-bounce-to-right">Add Review</button>
                                                    </div>
                                            	</div>
                                            </form>
                                        </div>


                                    </div>

                                </div>
                            </div>

                        </div>

                    </section>

                </div><!--End Content Side-->



                <!--Sidebar-->
                <div class="sidebar-side col-lg-3 col-md-4 col-sm-6 col-xs-12">
                    <aside class="sidebar">

                        <!-- Search Form todo 搜索功能-->
                        <div class="widget search-box sidebar-widget">

                            <form method="post" action="{% url 'shop:search' %}">
                                {% csrf_token %}
                                <div class="form-group">
                                    <input type="search" name="product_name" value="" placeholder="商品名称">
                                    <button type="submit"><span class="icon fa fa-search"></span></button>
                                </div>
                            </form>

                        </div>

                        <!-- Popular Categories -->
                        <div class="widget popular-categories sidebar-widget">
                            <div class="sidebar-title"><h3>Product Categories</h3></div>

                            <ul class="list-three">
                                {% for category in categories %}
                                    <li><a href="{% url 'shop:category' category.id %}">{{ category.name }} ({{ category.product_set.count }})</a></li>
                                {% endfor %}
                            </ul>

                        </div>

                        <!-- Price Filter -->
                        <div class="widget rangeslider-widget sidebar-widget">
                            <div class="sidebar-title"><h3>Filter By Price</h3></div>

                            <div class="range-slider-price" id="range-slider-price"></div>

                            <br>
                            <div class="form-group">
                                <form action="{% url 'shop:price_filter' %}" method="post">
                                    {% csrf_token %}
                                    <input type="text" class="val-box" id="min-value-rangeslider" name="minvalue">
                                    <input type="text" class="val-box" id="max-value-rangeslider" name="maxvalue">
                                    <button type="submit">Filter ($)</button>
                                </form>

                            </div>
                        </div>

                        <!-- Best Sellers -->
                        <div class="widget best-sellers sidebar-widget">
                        	<div class="sidebar-title"><h3>Latest Products</h3></div>

                            {% for product in latest_products %}
                                <div class="item">
                                <div class="post-thumb"><a href="{% url 'shop:shop_single' product.id %}"><img src="/static/media/{{ product.image }}" alt=""></a></div>
                                <h4><a href="{% url 'shop:shop_single' product.id %}">{{ product.name }}</a></h4>
                                <div class="rating"><span class="fa fa-star"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span></div>
                                <div class="item-price">$ {{ product.price }} <span class="strike-through">$ {{ product.price|add:51 }}</span></div>
                                </div>
                            {% endfor %}

                        </div>

                        <!-- Popular Tags -->
                        <div class="widget sidebar-widget popular-tags">

                            <div class="sidebar-title"><h3>产品标签</h3></div>
                            {% for tag in tags %}
                                <a href="{% url 'shop:tag' tag.id %}">{{ tag.name }}</a>
                            {% endfor %}

                        </div>

                    </aside>
                </div><!--End Sidebar-->

            </div>
        </div>
    </div>
{% endblock %}}

templates/shop/shop.html
{% extends 'shop/base.html' %}

{% block title %}
    shop
{% endblock %}

{% block body %}


     <!--Page Title-->
    <section class="page-title" style="background-image:url(/static/images/background/bg-page-title-1.jpg);">
        <div class="auto-container">
            <h1>Shop Products</h1>
        </div>
    </section>

    <!--Page Info-->
    <section class="page-info">
        <div class="auto-container clearfix">
            <div class="pull-left"><h2>Shop Products</h2></div>
            <div class="pull-right">
                <ul class="bread-crumb clearfix">
                    <li><a href="{% url 'firm:index' %}">Home</a></li>
                    <li><a href="{% url 'shop:shop' %}">Shop</a></li>
                    <li>Shop Products</li>
                </ul>
            </div>
        </div>
    </section>


    <!--Sidebar Page-->
    <div class="sidebar-page-container">
        <div class="auto-container">
            <div class="row clearfix">

                <!--Content Side-->
                {% block content %}
                <div class="content-side col-lg-9 col-md-8 col-sm-12 col-xs-12">

                    <!--Products Section-->
                    <section class="products-section no-padd-top">

                        <div class="shop-upper-box">
                            <div class="clearfix">
                                <div class="pull-left items-label">商品列表</div>
                            </div>
                        </div>

                        <div class="row clearfix">

                            {% for product in products %}
                                <div class="default-shop-item col-lg-4 col-md-6 col-sm-6 col-xs-12">
                                <!--inner-box-->
                                <div class="inner-box">
                                    <!--image-box-->
                                    <figure class="image-box">
                                        <a href="{% url 'shop:shop_single' product.id %}"><img src="/static/media/{{ product.image }}" alt="" /></a>
                                    </figure>

                                    <!--lower-content-->
                                    <div class="lower-content">
                                        <h3><a href="{% url 'shop:shop_single' product.id %}">{{ product.name }}</a></h3>

                                        <div class="rating">
                                            <span class="fa fa-star"></span>
                                            <span class="fa fa-star"></span>
                                            <span class="fa fa-star"></span>
                                            <span class="fa fa-star"></span>
                                            <span class="fa fa-star"></span>
                                        </div>

                                        <div class="price">$ {{ product.price }} <span>$ {% widthratio product.price 2 3 %} </span></div>
                                        <div class="links-box">
                                            <a class="cart-btn" href="{% url 'shop:add_cart' product.id %}">添加到购物车</a>
                                            <a class="zoom-btn lightbox-image" href="{{ product.image }}" title="Image Caption Here"><span class="fa fa-search-plus" title="Quick View"></span></a>
                                        </div>
                                    </div>

                                </div>
                            </div>
                            {% endfor %}

                        </div>

                        <hr class="no-margin">

                        <!-- Styled Pagination TODO 分页功能 -->
                        <!-- 分页开始 -->
                        <div class="styled-pagination padd-top-30 text-left">
                            <ul>
                            <li><a href="?page=1">首页</a></li>
                                <li>
                                    {% if products.has_previous %}
                                        <a href="?page={{ products.previous_page_number }}" class="prev"><span class="fa fa-angle-left"></span></a>
                                    {% endif %}
                                </li>

                                {% for num in page_range %}
                                    {% if num == products.number %}
                                        <li><a href="#" class="active">{{ num }}</a></li>
                                    {% else %}
                                        <li><a href="?page={{ num }}">{{ num }}</a></li>
                                    {% endif %}
                                {% endfor %}

                                <li>
                                {% if products.has_next %}
                                    <a class='next' href="?page={{ products.next_page_number }}"><span class="fa fa-angle-right"></span></a>
                                {% endif %}
                                </li>
                            <li><a href="?page={{ products.paginator.num_pages }}">尾页</a></li>
                            </ul>
                        </div>
                    <!-- 分页结束 -->

                    </section>

                </div><!--End Content Side-->
                {% endblock %}


                <!--Sidebar-->
                <div class="sidebar-side col-lg-3 col-md-4 col-sm-6 col-xs-12">
                    <aside class="sidebar">

                        <!-- Search Form -->
                        <div class="widget search-box sidebar-widget">
                            <form method="post" action="{% url 'shop:search' %}">
                                {% csrf_token %}
                                <div class="form-group">
                                    <input type="search" name="product_name" value="" placeholder="商品名字">
                                    <button type="submit"><span class="icon fa fa-search"></span></button>
                                </div>
                            </form>

                        </div>

                        <!-- Popular Categories -->
                        <div class="widget popular-categories sidebar-widget">
                            <div class="sidebar-title"><h3>Product Categories</h3></div>

                            <ul class="list-three">
                                {% for category in categories %}
                                    <li><a href="{% url 'shop:category' category.id %}">{{ category.name }} ({{ category.product_set.count }})</a></li>
                                {% endfor %}
                            </ul>

                        </div>

                        <!-- Price Filter -->
                        <div class="widget rangeslider-widget sidebar-widget">
                            <div class="sidebar-title"><h3>Filter By Price</h3></div>

                            <div class="range-slider-price" id="range-slider-price"></div>

                            <br>
                            <div class="form-group">
                                <form action="{% url 'shop:price_filter' %}" method="post">
                                    {% csrf_token %}
                                    <input type="text" class="val-box" id="min-value-rangeslider" name="minvalue">
                                    <input type="text" class="val-box" id="max-value-rangeslider" name="maxvalue">
                                    <button type="submit">Filter ($)</button>
                                </form>

                            </div>
                        </div>

                        <!-- Best Sellers -->
                        <div class="widget best-sellers sidebar-widget">
                        	<div class="sidebar-title"><h3>Latest Products</h3></div>

                            {% for product in latest_products %}
                                <div class="item">
                                <div class="post-thumb"><a href="{% url 'shop:shop_single' product.id %}"><img src="/static/media/{{ product.image }}" alt=""></a></div>
                                <h4><a href="{% url 'shop:shop_single' product.id %}">{{ product.name }}</a></h4>
                                <div class="rating"><span class="fa fa-star"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span></div>
                                <div class="item-price">$ {{ product.price }} <span class="strike-through">$ {{ product.price|add:51 }}</span></div>
                                </div>
                            {% endfor %}

                        </div>

                        <!-- Popular Tags -->
                        <div class="widget sidebar-widget popular-tags">

                            <div class="sidebar-title"><h3>产品标签</h3></div>
                            {% for tag in tags %}
                                <a href="{% url 'shop:tag' tag.id %}">{{ tag.name }}</a>
                            {% endfor %}

                        </div>

                    </aside>
                </div><!--End Sidebar-->

            </div>
        </div>
    </div>
{% endblock %}