DecoratorDesign/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('',include('firm.urls',namespace='firm')),
    url('shop/', include('shop.urls', namespace='shop')),
    url('blog/',include('blog.urls',namespace='blog')),
    url('project/',include('furnitureapp.urls',namespace='furnitureapp')),
]

blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from .views import *
# 全文搜索
from haystack.views import SearchView


app_name = 'blog'

urlpatterns = [
    url(r'^register/$', register, name='register'),
    url(r'^$', login, name='login'),
    url(r'^public/$', public, name='public'),
    url(r'^total/$', total, name='total'),
    url(r'^single/(\d+)/$', single, name='single'),
    url(r'^see/$', see, name='see'),
    url(r'^large_total/$', large_total, name='large_total'),
    # 全文搜索，调用第三方库中的视图函数
    url(r'^search/$', SearchView(), name='search'),

]

firm/urls.py
from django.conf.urls import url
from . import views

app_name = 'firm'


urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^pricing/$',views.pricing,name='pricing'),
    url(r'^question/$', views.faqs,name='question'),
    url(r'^team-single/(\d+)/$',views.team_single,name='team-single'),
    url(r'^team/$',views.team,name='team'),
    url(r'^about/$',views.about,name='about'),
]

firm/models.py
from django.db import models

# Create your models here.


class Service(models.Model):
    title = models.CharField(max_length=30)
    message = models.TextField()
    span = models.CharField(max_length=100,null=True,blank=True)


class Trait(models.Model):
    span = models.CharField(max_length=80)
    title = models.CharField(max_length=80)
    message = models.TextField()


class Stylist(models.Model):
    message = models.TextField()
    image = models.TextField()
    name = models.CharField(max_length=50)


class ShopList(models.Model):
    image = models.TextField()
    title = models.CharField(max_length=80)
    price = models.CharField(max_length=50)
    new_price = models.CharField(max_length=50)


class Pricing(models.Model):
    '''价格定价页'''
    title = models.CharField(max_length=50)
    pricing = models.IntegerField()
    text1 = models.TextField()
    text2 = models.TextField()
    text3 = models.TextField()
    text4 = models.TextField()


class Question(models.Model):
    '''疑问解惑也的问题'''
    question = models.TextField()
    message = models.TextField()

class Potential(models.Model):
    '''潜在用户表，客户提交问题'''
    username = models.CharField(max_length=50)
    email = models.EmailField()
    phone = models.IntegerField()
    question = models.TextField()

class Team(models.Model):
    '''公司团队'''
    name= models.CharField(max_length=50)
    message = models.TextField()
    image = models.TextField()
    profession = models.CharField(max_length=50)
    addr = models.TextField(null=True,blank=True)
    email = models.EmailField(null=True,blank=True)
    phone = models.IntegerField(null=True,blank=True)

    def __str__(self):
        return self.name

class Education(models.Model):
    '''团队成员教育史'''
    school = models.CharField(max_length=100)
    time = models.TextField()
    message = models.TextField()
    teamid = models.ForeignKey(Team,on_delete=models.CASCADE)

firm/forms.py
from django import forms
from .models import Potential


class PotentialForm(forms.ModelForm):
    class Meta:
        model = Potential
        fields = ['username','email','phone','question']

firm/views.py
from django.shortcuts import render,reverse,redirect
from django.http import HttpResponse
from .models import *
from .forms import PotentialForm
# Create your views here.


def index(request):
    services = Service.objects.all()
    traits = Trait.objects.all()
    stylists = Stylist.objects.all()
    shoplists = ShopList.objects.all()
    data = {'services':services,'traits':traits,'stylists':stylists,'shoplists':shoplists}
    return render(request,'firm/index.html',data)


def pricing(request):
    pricings = Pricing.objects.all()
    return render(request,'firm/pricing.html',{'pricings':pricings})


def faqs(request):
    if request.method == 'GET':
        questions = Question.objects.all().order_by('-id')[:6]
        return render(request,'firm/faqs.html',{'questions':questions})
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        phone = request.POST['number']
        question = request.POST['message']
        print(username,email,phone,question)
        user = Potential()
        user.username = username
        user.email = email
        user.phone = phone
        user.question = question
        user.save()
        return redirect(reverse("firm:question"))


def team_single(request,id):
    parents = Team.objects.all()
    parent = Team.objects.get(pk=id)
    team_details = Team.objects.get(pk=id).education_set.all()
    ids = int(id)
    ss = {'parents':parents,'details':team_details,'id':ids,'user':parent}
    return render(request,'firm/team-single.html',ss)


def team(request):
    team_list = Team.objects.all()
    return render(request,'firm/team.html',{'team_list':team_list})


def about(request):
    parents = Team.objects.all()[:4]
    return render(request,'firm/about.html',{'parents':parents})

templates/firm/faqs.html
{% extends 'firm/base.html' %}

{% block title %}
    疑问解答页
{% endblock %}

{% block body %}
    <section class="page-title" style="background-image:url(/static/images/background/bg-page-title-1.jpg);">
        <div class="auto-container">
            <h1>FAQ's</h1>
        </div>
    </section>

    <section class="page-info">
        <div class="auto-container clearfix">
            <div class="pull-left"><h2>常见问题解答</h2></div>
            <div class="pull-right">
                <ul class="bread-crumb clearfix">
                    <li><a href="{% url 'firm:index' %}">Home</a></li>
                    <li><a href="{% url 'firm:index' %}">Pages</a></li>
                    <li>FAQ's</li>
                </ul>
            </div>
        </div>
    </section>

    <section class="faqs-section">
    	<div class="auto-container">

            <div class="faqs-container">
            	<!--Accordion Box-->
                <ul class="accordion-box">

                    {% for q in questions %}

                        <li class="accordion block wow fadeInUp" data-wow-delay="0ms" data-wow-duration="1500ms">
                        <div class="acc-btn">
                            <div class="icon-outer">
                                <span class="icon icon-plus fa fa-angle-right"></span>
                                <span class="icon icon-minus fa fa-angle-down"></span>
                            </div>{{ q.question }}
                        </div>
                        <div class="acc-content">
                            <div class="content clearfix">
                                <p>{{ q.message }} </p>
                            </div>
                        </div>
                    </li>

                    {% endfor %}


                </ul>
            </div>

            <div class="sec-title medium">
            	<h2>请输入问题</h2>
            </div>

            <div class="ask-questions">
            	<!--form-box-->
                <div class="form-box default-form">
                    <div class="contact-form default-form">
                        <form method="post" action="">
                            {% csrf_token %}
                            <div class="row clearfix">

                                <div class="form-group col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" name="username" value="" placeholder="Your Name *" required>
                                </div>

                                <div class="form-group col-md-6 col-sm-6 col-xs-12">
                                    <input type="email" name="email" value="" placeholder="Email Address *" required>
                                </div>

                                <div class="form-group col-md-6 col-sm-6 col-xs-12">
                                    <input type="text" name="number" value="" placeholder="Phone">
                                </div>

                                <div class="form-group col-md-12 col-sm-12 col-xs-12">
                                    <textarea name="message" placeholder="Your Question"></textarea>
                                </div>

                                <div class="form-group col-md-12 col-sm-12 col-xs-12">
                                    <button type="submit" class="theme-btn btn-style-two">请提交</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </section>
{% endblock %}

templates/firm/pricing.html
{% extends 'firm/base.html' %}

{% block title %}
    报价页
{% endblock %}

{% block body %}
    <section class="page-title" style="background-image:url(/static/images/background/bg-page-title-1.jpg);">
        <div class="auto-container">
            <h1>服务  报价</h1>
        </div>
    </section>

    <section class="page-info">
        <div class="auto-container clearfix">
            <div class="pull-left"><h2>服务报价</h2></div>
            <div class="pull-right">
                <ul class="bread-crumb clearfix">
                    <li><a href="{% url 'firm:index' %}">Home</a></li>
                    <li><a href="{% url 'firm:index' %}">Pages</a></li>
                    <li>服务报价</li>
                </ul>
            </div>
        </div>
    </section>

    <section class="pricing-section">
    	<div class="auto-container">

            <div class="sec-title medium">
            	<h2>团队服务标准</h2>
                <div class="desc-text">

                </div>
            </div>

        	<div class="row clearfix">

                {% for pricing in pricings %}
                    <div class="pricing-column col-lg-3 col-md-4 col-sm-6 col-xs-12">
                	<div class="inner-box">
                    	<div class="plan-title">{{ pricing.title }}</div>
                        <div class="price-header"><span class="price"><sup>$</sup>{{ pricing.pricing }}</span> <sub>/ Month</sub></div>
                        <div class="lower-content">
                        	<ul class="spec-list">
                                <li>{{ pricing.text1 }}</li>
                                <li>{{ pricing.text2 }}</li>
                                <li>{{ pricing.text3 }}</li>
                                <li>{{ pricing.text4 }}</li>
                            </ul>

                            <a href="#" class="theme-btn btn-style-two">立即购买</a>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
    </section>

    <section class="call-to-action-one">
    	<div class="auto-container">
        	<div class="clearfix">

                <div class="pull-left">
                	<h3>我们为每位客户提供全面而具体的解决方案，并提供我们的后续服务。</h3>
                </div>
                <div class="pull-right">
                	<a href="" class="theme-btn btn-style-two">立即购买</a>
                </div>

            </div>
        </div>
    </section>
{% endblock %}

templates/firm/team-single.html
{% extends 'firm/base.html' %}

{% block title %}
    团队详情页
{% endblock %}

{% block body %}
    <section class="page-title" style="background-image:url(/static/images/background/bg-page-title-1.jpg);">
        <div class="auto-container">
            <h1>精英团队</h1>
        </div>
    </section>

    <section class="page-info">
        <div class="auto-container clearfix">
            <div class="pull-left"><h2>精英团队</h2></div>
            <div class="pull-right">
                <ul class="bread-crumb clearfix">
                    <li><a href="index.html">Home</a></li>
                    <li><a href="index.html">Pages</a></li>
                    <li>Elite Team</li>
                </ul>
            </div>
        </div>
    </section>

    <div class="sidebar-page-container">
        <div class="auto-container">
            <div class="row clearfix">

                <!--Sidebar-->
                <div class="sidebar-side col-lg-3 col-md-4 col-sm-12 col-xs-12">
                    <aside class="sidebar">

                        <!--Sidebar Widget / Boxed Nav-->
                        <div class="widget sidebar-widget styled-nav">
                            <nav class="nav-outer">
                                <ul>
                                    {% for parent in parents %}
                                        {% if id == parent.id %}
                                            <li class="current" ><a href="{% url 'firm:team-single' parent.id %}">{{ parent.name }}</a></li>
                                        {% else %}
                                            <li><a href="{% url 'firm:team-single' parent.id %}">{{ parent.name }}</a></li>
                                        {% endif %}

                                    {% endfor %}
                                    
                                </ul>

                            </nav>
                        </div>

                        <!--Sidebar Widget / Downloads-->
                        <div class="widget sidebar-widget downloads">
                            <div class="sidebar-title"><h3>Our Brochures</h3></div>
                            <ul>
                                <li><a href="#"><span class="icon fa fa-file-pdf-o"></span> Download.Pdf</a></li>
                                <li><a href="#"><span class="icon fa fa-file-word-o"></span> Download.Doc</a></li>
                            </ul>
                        </div>

                        <!--Sidebar Widget / Testimonials-->
                        <div class="widget sidebar-widget testimonials">
                            <div class="sidebar-title"><h3>Testimonials</h3></div>
                            <div class="single-item-carousel">

                                <!--Slide Item-->
                                <div class="slide-item">
                                    <div class="upper-content">
                                        <div class="text">
                                            他们按时组织我的项目，组织良好，工程师团队经验丰富。
                                        </div>
                                    </div>
                                    <div class="testi-info">
                                        <figure class="author-thumb img-circle"><img class="img-circle" src="/static/images/resource/author-thumb-4.jpg" alt=""></figure>
                                        <h4>马克.威廉 - <span class="designation">中国移动上海分公司 CEO</span> </h4>
                                        <div class="rating"><span class="fa fa-star"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span></div>
                                    </div>
                                </div>

                                <!--Slide Item-->
                                <div class="slide-item">
                                    <div class="upper-content">
                                        <div class="text">我们享受到了专业，周到，舒适的服务。而且设计产品与实际效果都很不错。</div>
                                    </div>
                                    <div class="testi-info">
                                        <figure class="author-thumb img-circle"><img class="img-circle" src="/static/images/resource/user-1.jpg" alt=""></figure>
                                        <h4>刘小康 - <span class="designation">香港著名设计师</span> </h4>
                                        <div class="rating"><span class="fa fa-star"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span></div>
                                    </div>
                                </div>

                                <!--Slide Item-->
                                <div class="slide-item">
                                    <div class="upper-content">
                                        <div class="text">
                                            不错的团队，尤其是其专业的设计功底。我们很感谢他们的帮助，让我们的顾客感受非凡。
                                        </div>
                                    </div>
                                    <div class="testi-info">
                                        <figure class="author-thumb img-circle"><img class="img-circle" src="/static/images/resource/user-2.png" alt=""></figure>
                                        <h4> 吕珊洲- <span class="designation">上海市艾美养生有限公司 CEO</span> </h4>
                                        <div class="rating"><span class="fa fa-star"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span></div>
                                    </div>
                                </div>

                            </div>
                        </div>

                    </aside>
                </div><!--End Sidebar-->

                <!--Content Side-->
                <div class="content-side col-lg-9 col-md-8 col-sm-12 col-xs-12">
                    <!--Team Single-->
                    <section class="team-member-single">

                        <!--Basic Details-->
                        <div class="basic-details">
                            <div class="row clearfix">
                                <div class="image-column col-md-4 col-sm-6 col-xs-12">
                                    <figure class="image-box"><img class="img-responsive" src="{{ user.image }}" alt=""></figure>
                                </div>
                                <div class="info-column col-md-8 col-sm-12 col-xs-12">
                                    <div class="info-header">
                                        <h2 class="member-title">{{ user.name }}</h2>
                                        <div class="designation">{{ user.profession }}</div>
                                    </div>

                                    <div class="quoted-text">He is a Team Leader of Decorators With Over 12 Years of Experience.</div>

                                    <div class="desc-text">{{ user.message }}</div>

                                    <div class="social-links">
                                        <a href="#"><span class="fa fa-facebook-f"></span></a>
                                        <a href="#"><span class="fa fa-twitter"></span></a>
                                        <a href="#"><span class="fa fa-google-plus"></span></a>
                                        <a href="#"><span class="fa fa-linkedin"></span></a>
                                    </div>

                                </div>
                            </div>
                        </div><!--Basic Details-->

                        <!--Educational Details-->
                        <div class="educational-details">
                            <div class="sec-title medium"><h2>教育经历</h2></div>

                            <div class="row clearfix">

                                {% for detail in details %}
                                     <div class="block col-md-6 col-sm-6 col-xs-12">
                                        <div class="inner-box">
                                            <div class="icon-box"><span class="fa fa-graduation-cap"></span></div>
                                            <h3>{{ detail.school }}</h3>
                                            <div class="text"><span class="theme_color">{{ detail.time }}</span>{{ detail.message }}</div>
                                        </div>
                                    </div>
                                {% endfor %}


                            </div>
                        </div>

                        <!--Experties Details-->
                        <div class="experties">
                            <div class="sec-title medium"><h2>专业领域</h2></div>

                            <!--Experties Carousel-->
                            <div class="experties-carousel">
                                <!--Experties Block-->
                                <div class="expert-block">
                                    <div class="inner-box">
                                        <div class="icon-box"><span class="flaticon-improvement"></span></div>
                                        <h4>Texture Painting</h4>
                                        <div class="overlay-box">
                                            <div class="over-inner">
                                                <div class="content">精致的人生，需要专业的团队。 </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <!--Experties Block-->
                                <div class="expert-block">
                                    <div class="inner-box">
                                        <div class="icon-box"><span class="flaticon-crate"></span></div>
                                        <h4>Wooden FLooring</h4>
                                        <div class="overlay-box">
                                            <div class="over-inner">
                                                <div class="content">精致的人生，需要专业的团队。 </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <!--Experties Block-->
                                <div class="expert-block">
                                    <div class="inner-box">
                                        <div class="icon-box"><span class="flaticon-bright-lightbulb"></span></div>
                                        <h4>Lighting Works</h4>
                                        <div class="overlay-box">
                                            <div class="over-inner">
                                                <div class="content">精致的人生，需要专业的团队。 </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <!--Experties Block-->
                                <div class="expert-block">
                                    <div class="inner-box">
                                        <div class="icon-box"><span class="flaticon-compass"></span></div>
                                        <h4>Interior</h4>
                                        <div class="overlay-box">
                                            <div class="over-inner">
                                                <div class="content">精致的人生，需要专业的团队。</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>

                        </div>

                         <!--Contact Now-->
                        <div class="contact-now">
                            <div class="sec-title medium"><h2>联系方式</h2></div>

                            <div class="row clearfix">
                                <!--Column-->
                                <div class="column col-lg-5 col-md-6 col-sm-6 col-xs-12" style="width: 100%;margin-left: 150px;">
                                    <div class="info-style-one">
                                        <ul>
                                            <li><div class="icon-box"><span class="flaticon-international-delivery"></span></div><h4>地址 :</h4><div class="text">{{ user.addr }}</div></li>
                                            <li><div class="icon-box"><span class="flaticon-envelope"></span></div><h4>邮箱地址:</h4><div class="text">{{ user.email }}</div></li>
                                            <li><div class="icon-box"><span class="flaticon-phone-call"></span></div><h4>电话:</h4><div class="text"> {{ user.phone }}</div></li>
                                        </ul>
                                    </div>
                                </div>

                            </div>
                        </div>


                    </section>
                </div><!--End Content Side-->

            </div>
        </div>
    </div>

{% endblock %}

templates/firm/team.html
{% extends 'firm/base.html' %}

{% block title %}
    团队列表页
{% endblock %}

{% block body %}
    <section class="page-title" style="background-image:url(/static/images/background/bg-page-title-1.jpg);">
        <div class="auto-container">
            <h1>完美作品的缔造者</h1>
        </div>
    </section>

    <section class="page-info">
        <div class="auto-container clearfix">
            <div class="pull-left"><h2>团队成员</h2></div>
            <div class="pull-right">
                <ul class="bread-crumb clearfix">
                    <li><a href="index.html">Home</a></li>
                    <li><a href="index.html">Pages</a></li>
                    <li>Team</li>
                </ul>
            </div>
        </div>
    </section>

    <section class="team-section-one">
    	<div class="auto-container">

            <div class="row clearfix">

                {% for team in team_list %}
                    <div class="team-member-one col-lg-3 col-md-4 col-sm-6 col-xs-12">
                	<div class="inner-box">
                    	<figure class="image-box">
                            <img src="{{ team.image }}" alt="">
                            <a href="{% url 'firm:team-single' team.id %}">
                                <div class="overlay"></div>>
                            </a>
                        </figure>
                        <div class="lower-content">
                        	<h3><a href="{% url 'firm:team-single' team.id %}">{{ team.name }}</a></h3>
                            <div class="designation">{{ team.profession }}</div>
                            <div class="desc-text">{{ team.message }}</div>
                            <div class="links-box"><a class="theme-btn read-more" href="{% url 'firm:team-single' team.id %}">查看<span class="fa fa-caret-right"></span></a></div>
                        </div>
                    </div>
                </div>
                {% endfor %}


            </div>

        </div>
    </section>
{% endblock %}