DecoratorDesign/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('',include('firm.urls',namespace='firm')),
    url('shop/', include('shop.urls', namespace='shop')),
    url('blog/',include('blog.urls',namespace='blog')),
    url('project/',include('furnitureapp.urls',namespace='furnitureapp')),
]

blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from .views import *
# 全文搜索
from haystack.views import SearchView


app_name = 'blog'

urlpatterns = [
    url(r'^register/$', register, name='register'),
    url(r'^$', login, name='login'),
    url(r'^public/$', public, name='public'),
    url(r'^total/$', total, name='total'),
    url(r'^single/(\d+)/$', single, name='single'),
    url(r'^see/$', see, name='see'),
    url(r'^large_total/$', large_total, name='large_total'),
    # 全文搜索，调用第三方库中的视图函数
    url(r'^search/$', SearchView(), name='search'),

]

furnitureapp/urls.py
from django.conf.urls import url
from . import views

app_name = 'furnitureapp'
urlpatterns = [
    url('^$', views.portfoli, name='portfoli'),
    url(r'^defalut/(\d+)/$', views.defalut, name='defalut'),
    url(r'^singletwo/(\d+)/(\d+)/$', views.singletwo, name='singletwo'),
    url(r'^fullwidth/$',views.fullwidth, name='fullwidth'),
    url(r'^pictext/$',views.pictext,name='pictext'),
    url(r'^sendemail/$',views.sendemail,name='sendemail')
]

furnitureapp/models.py
from django.db import models
from tinymce.models import HTMLField


# Create your models here.
class UserInfo(models.Model):
    subject = models.CharField(max_length=26,null=True,blank=True)
    name = models.CharField(max_length=16)
    email = models.EmailField()
    phonenumber = models.CharField(max_length=13,null=True)
    message = models.TextField(max_length=660,null=True)

    def __str__(self):
        return self.name


class Classify(models.Model):
    classify = models.CharField(max_length=16)

    def __str__(self):
        return self.classify


class Furniture(models.Model):
    imgname = models.CharField(max_length=16)
    indexn = models.SmallIntegerField()
    img = models.ImageField(upload_to='hotpic')
    classifies = models.ManyToManyField(Classify)

    def __str__(self):
        return self.imgname


class FurnitureInfo(models.Model):
    tag = models.CharField(max_length=90)
    pub_date = models.DateTimeField(null=True, blank=True)
    author = models.CharField(max_length=26)
    tagweb = models.URLField(max_length=36)
    tofu = models.ForeignKey(Furniture, models.CASCADE)
    title = models.CharField(max_length=150)
    descirbe = HTMLField()

    def __str__(self):
        return self.title


class Furnitureimg(models.Model):
    name = models.CharField(max_length=16)
    furimg = models.ImageField(upload_to='hotpic')
    index = models.SmallIntegerField()
    fore = models.ForeignKey(Furniture, models.CASCADE)

    def __str__(self):
        return self.name


class FullWidth(models.Model):
    name = models.CharField(max_length=16)
    fullpic = models.ImageField(upload_to='fullwidth')
    fyr = models.ForeignKey(Classify, models.CASCADE,null=True, blank=True)

    def __str__(self):
        return self.name


class TextPic(models.Model):
    tag = models.CharField(max_length=16)
    deti = models.CharField(max_length=16)
    img = models.ImageField(upload_to='textimg')
    fyr = models.ForeignKey(Classify, models.CASCADE,null=True, blank=True)

    def __str__(self):
        return self.tag


class SingTwo(models.Model):
    singimg = models.ImageField(upload_to='singtwo')
    name = models.CharField(max_length=16)
    sfor = models.ForeignKey(FullWidth, models.CASCADE, null=True, blank=True)
    timgfy = models.ForeignKey(TextPic, models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.name

furnitureapp/views.py
from django.shortcuts import render, redirect
from .models import *
from django.core.paginator import Paginator
from django.conf import settings
from django.core.mail import send_mail
from django.http import HttpResponse


# Create your views here.
def getpage(request, objectlist):
    paginatorlist = Paginator(objectlist, 9)
    pagenum = request.GET.get("page")
    pagenum = 1 if pagenum == None else pagenum
    page = paginatorlist.page(pagenum)
    return page


def portfoli(request):
    classify = Classify.objects.all()
    indeximg = Furniture.objects.all()
    return render(request, 'furnitureapp/portfolio-default.html', {'classifies': classify, 'indeximgs': indeximg})


def defalut(request, id):
    indeximg = Furniture.objects.get(pk=id)
    furnitureinfo = indeximg.furnitureinfo_set.all()
    furnitureimg = indeximg.furnitureimg_set.all()
    return render(request, 'furnitureapp/portfolio-single-one.html',
                  {'furnitureInfo': furnitureinfo, 'furnitureimg': furnitureimg})


def singletwo(request, id, fid):
    articles = FurnitureInfo.objects.get(pk=id)
    slp = FullWidth.objects.get(pk=fid)
    img = SingTwo.objects.filter(sfor=slp).all()
    return render(request, 'furnitureapp/portfolio-single-two.html', {'pics': img, 'articles': articles})


def fullwidth(request):
    classify = Classify.objects.all()
    wpic = FullWidth.objects.all()
    return render(request, 'furnitureapp/portfolio-fullwidth.html', {'classify': classify, 'wpics': wpic})


def pictext(request):
    classify = Classify.objects.all()
    textimg = TextPic.objects.all()
    page = getpage(request, textimg)
    return render(request, 'furnitureapp/portfolio-with-text.html', {'classify': classify, 'textimg': page, 'page': page})


def sendemail(request):
    if request.method == 'GET':
        return render(request, 'furnitureapp/contact.html')
    elif request.method == 'POST':
        userinfo = UserInfo(subject=request.POST['subject'], name=request.POST['username'], email=request.POST['email'],
                            phonenumber=request.POST['phone'], message=request.POST['message'])
        userinfo.save()
        email = userinfo.email
        send_mail("we find out you message. later send you",
                  "There are many variations off +1800 854 5864 available, "
                  "but the majority have ut suffered alterattions in some"
                  " forms by injected humour looks events slightly "
                  "seds believable ut seds do eiusmod tempor incididunt labore.",
                  settings.DEFAULT_FROM_EMAIL, [email])
        return HttpResponse('sended')

templates/furnitureapp/contact.html
{% extends 'furnitureapp/base.html' %}
{% block page %}Contact Us{% endblock %}
{% block usf %}<li class="dropdown"><a href="#">Projects</a>{% endblock %}
{% block urf %}<li class="current"><a href="{% url 'furnitureapp:sendemail' %}">Contact</a></li>{% endblock %}
{% block body %}
 <section class="contact-section">
    	<div class="auto-container">
        	<div class="row clearfix">

                <!--Form Column -->
            	<div class="column form-column col-lg-6 col-md-12 col-sm-12 col-xs-12">
                	<div class="sec-title medium"><h2>Send Message Us</h2></div>
                	<!--form-box-->
                    <div class="form-box default-form">
                        <div class="contact-form default-form">
                            <form method="post" action="{% url 'furnitureapp:sendemail' %}" id="contact-form">
                                {% csrf_token %}
                                <div class="row clearfix">

                                    <div class="form-group col-md-6 col-sm-6 col-xs-12">
                                        <select name="subject">
                                            <option>Subject</option>
                                            <option>Wooden Flooring</option>
                                            <option>Metal Flooring</option>
                                            <option>Concrete Flooring</option>
                                        </select>
                                    </div>

                                    <div class="form-group col-md-6 col-sm-6 col-xs-12">
                                        <input type="text" name="username" value="" placeholder="Your Name *" required>
                                    </div>

                                    <div class="form-group col-md-6 col-sm-6 col-xs-12">
                                        <input type="email" name="email" value="" placeholder="Your Mail *" required>
                                    </div>

                                    <div class="form-group col-md-6 col-sm-6 col-xs-12">
                                        <input type="text" name="phone" value="" placeholder="Phone Number">
                                    </div>

                                    <div class="form-group col-md-12 col-sm-12 col-xs-12">
                                        <textarea name="message" placeholder="Message *"></textarea>
                                    </div>
                                    <div class="form-group col-md-12 col-sm-12 col-xs-12">
                                        <button type="submit" class="theme-btn btn-style-two">Get Quote</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

                <!--Column-->
                <div class="column info-column col-lg-6 col-md-6 col-sm-12 col-xs-12">
                	<div class="sec-title medium"><h2>Contact Details</h2></div>
                    <div class="desc-text">There are many variations off +1800 854 5864 available, but the majority have ut suffered alterattions in some forms by injected humour looks events slightly seds believable ut  seds do eiusmod tempor incididunt labore.</div>
                	<div class="info-style-one">
                        <ul>
                            <li><div class="icon-box"><span class="flaticon-international-delivery"></span></div><h4>Address :</h4><div class="text">21/17, Level 4 Steel Rock St, Melbourne <br>Victoria 3000, Australia.</div></li>
                            <li><div class="icon-box"><span class="flaticon-envelope"></span></div><h4>Mail to Fernando :</h4><div class="text">Decoratorssupport@gmail.com</div></li>
                            <li><div class="icon-box"><span class="flaticon-phone-call"></span></div><h4>Call Him:</h4><div class="text"> +1 (44) 123-45-67, +1(44) 456-78-90</div></li>
                        </ul>
                    </div>
                </div>

            </div>
       	</div>
   	</section>


    <!--Map Section-->
    <section class="map-section">
    	<div class="map-outer">

            <!--Map Canvas-->
            <div class="map-canvas"
                data-zoom="10"
                data-lat="23.815811"
                data-lng="90.412580"
                data-type="roadmap"
                data-hue="#fc721e"
                data-title="Dhaka"
                data-content="Dhaka 1000-1200, Bangladesh<br><a href='mailto:info@youremail.com'>info@youremail.com</a>"
                style="height:480px;">
            </div>

        </div>
    </section>
{% endblock %}
{% block link %}
<script src="/static/js/jquery.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/jquery.mCustomScrollbar.concat.min.js"></script>
<script src="/static/js/jquery.fancybox.pack.js"></script>
<script src="/static/js/jquery.fancybox-media.js"></script>
<script src="/static/js/validate.js"></script>
<script src="/static/js/owl.js"></script>
<script src="/static/js/wow.js"></script>
<script src="/static/js/script.js"></script>

<!--Google Map APi Key-->
<script src="/static/js/map-script.js"></script>
<!--End Google Map APi-->
{% endblock %}

templates/furnitureapp/portfolio-default.html
{% extends 'furnitureapp/base.html' %}

{% block body %}
    <!--Gallery Section-->
    <section class="gallery-section">
    	<div class="auto-container">

            <!--Sortable Masonry-->
            <div class="sortable-masonry">
                <!--Filter-->
                <div class="filters text-center">
                <div class="icon-box"><span class="fa fa-picture-o"></span></div>

                    <ul class="filter-tabs filter-btns clearfix">
                        <li class="active filter" data-role="button" data-filter=".all">All Projects</li>
                        {% for cls in classifies %}
                        <li class="filter" data-role="button" data-filter=".{{ cls.classify.lower }}">{{ cls.classify }}</li>
                        {% endfor %}
                    </ul>
                </div>




                <div class="items-container clearfix">
 {% for img in indeximgs %}
                    <!--Default Portfolio Item-->
                {% if img.indexn == 1 %}
                    <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 default-portfolio-item masonry-item all tile-marble">
                        <div class="inner-box">
                            <figure class="image-box"><img src="/static/media/{{ img.img.name }}" alt=""></figure>
                            <!--Overlay Box-->
                            <div class="overlay-one">
                                <div class="overlay-inner">
                                    <div class="content">
                                        <a href="{% url 'furnitureapp:defalut' img.id %}" class="proj-link"><span class="fa fa-link"></span></a>
                                    </div>
                                </div>
                            </div>
                            <!--Caption Box-->
                            <div class="caption-box-one">
                            	<h3><a href="{% url 'furnitureapp:defalut' img.id %}">Living Room</a></h3>
                                <a href="#" class="cat-link">Painting</a>
                            </div>
                        </div>
                    </div>
                    {% endif %}

                    <!--Default Portfolio Item-->
                    {% if img.indexn == 2 %}
                    <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 default-portfolio-item masonry-item all tile-marble lighting">
                        <div class="inner-box">
                            <figure class="image-box"><img src="/static/media/{{ img.img.name }}" alt=""></figure>
                            <!--Overlay Box-->
                            <div class="overlay-one">
                                <div class="overlay-inner">
                                    <div class="content">
                                        <a href="{% url 'furnitureapp:defalut' img.id %}" class="proj-link"><span class="fa fa-link"></span></a>
                                    </div>
                                </div>
                            </div>
                            <!--Caption Box-->
                            <div class="caption-box-one">
                            	<h3><a href="{% url 'furnitureapp:defalut' img.id %}">Living Room</a></h3>
                                <a href="#" class="cat-link">Painting</a>
                            </div>
                        </div>
                    </div>
                {% endif %}

                    <!--Default Portfolio Item-->
                {% if img.indexn == 3 %}
                    <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 default-portfolio-item masonry-item all flooring tile-marble furniture lighting">
                        <div class="inner-box">
                            <figure class="image-box"><img src="/static/media/{{ img.img.name }}" alt=""></figure>
                            <!--Overlay Box-->
                            <div class="overlay-one">
                                <div class="overlay-inner">
                                    <div class="content">
                                        <a href="{% url 'furnitureapp:defalut' img.id %}" class="proj-link"><span class="fa fa-link"></span></a>
                                    </div>
                                </div>
                            </div>
                            <!--Caption Box-->
                            <div class="caption-box-one">
                            	<h3><a href="{% url 'furnitureapp:defalut' img.id %}">Living Room</a></h3>
                                <a href="#" class="cat-link">Painting</a>
                            </div>
                        </div>
                    </div>
                {% endif %}

                    <!--Default Portfolio Item-->
                {% if img.indexn == 4 %}
                    <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 default-portfolio-item masonry-item all painting flooring furniture">
                        <div class="inner-box">
                            <figure class="image-box"><img src="/static/media/{{ img.img.name }}" alt=""></figure>
                            <!--Overlay Box-->
                            <div class="overlay-one">
                                <div class="overlay-inner">
                                    <div class="content">
                                        <a href="{% url 'furnitureapp:defalut' img.id %}" class="proj-link"><span class="fa fa-link"></span></a>
                                    </div>
                                </div>
                            </div>
                            <!--Caption Box-->
                            <div class="caption-box-one">
                            	<h3><a href="{% url 'furnitureapp:defalut' img.id %}">Living Room</a></h3>
                                <a href="#" class="cat-link">Painting</a>
                            </div>
                        </div>
                    </div>
                {% endif %}

                    <!--Default Portfolio Item-->
                {% if img.indexn == 5 %}
                    <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 default-portfolio-item masonry-item all painting tile-marble furniture lighting">
                        <div class="inner-box">
                            <figure class="image-box"><img src="/static/media/{{ img.img.name }}" alt=""></figure>
                            <!--Overlay Box-->
                            <div class="overlay-one">
                                <div class="overlay-inner">
                                    <div class="content">
                                        <a href="{% url 'furnitureapp:defalut' img.id %}" class="proj-link"><span class="fa fa-link"></span></a>
                                    </div>
                                </div>
                            </div>
                            <!--Caption Box-->
                            <div class="caption-box-one">
                            	<h3><a href="{% url 'furnitureapp:defalut' img.id %}">Living Room</a></h3>
                                <a href="#" class="cat-link">Painting</a>
                            </div>
                        </div>
                    </div>
                {% endif %}

                    <!--Default Portfolio Item-->
                {% if img.indexn == 6 %}
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 default-portfolio-item masonry-item all painting flooring tile-marble">
                        <div class="inner-box">
                            <figure class="image-box"><img src="/static/media/{{ img.img.name }}" alt=""></figure>
                            <!--Overlay Box-->
                            <div class="overlay-one">
                                <div class="overlay-inner">
                                    <div class="content">
                                        <a href="{% url 'furnitureapp:defalut' img.id %}" class="proj-link"><span class="fa fa-link"></span></a>
                                    </div>

                                </div>
                            </div>
                            <!--Caption Box-->
                            <div class="caption-box-one">
                            	<h3><a href="{% url 'furnitureapp:defalut' img.id %}">Living Room</a></h3>
                                <a href="#" class="cat-link">Painting</a>
                            </div>
                        </div>
                    </div>
                {% endif %}

                    <!--Default Portfolio Item-->
                {% if img.indexn == 7 %}
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 default-portfolio-item masonry-item all flooring furniture lighting">
                        <div class="inner-box">
                            <figure class="image-box"><img src="/static/media/{{ img.img.name }}" alt=""></figure>
                            <!--Overlay Box-->
                            <div class="overlay-one">
                                <div class="overlay-inner">
                                    <div class="content">
                                        <a href="" class="proj-link"><span class="fa fa-link"></span></a>
                                    </div>
                                </div>
                            </div>
                            <!--Caption Box-->
                            <div class="caption-box-one">
                            	<h3><a href="">Living Room</a></h3>
                                <a href="#" class="cat-link">Painting</a>
                            </div>
                        </div>
                    </div>
            {% endif %}
                {% endfor %}

                </div>


            </div><!--End Sortable Masonry-->

            <div class="text-center padd-top-50"><a class="theme-btn btn-style-two" href="">More Projects</a></div>

        </div>



    </section>
{% endblock %}

templates/furnitureapp/portfolio-fullwidth.html
{% extends 'furnitureapp/base.html' %}
{% block page %}Projects Fullwidth{% endblock %}
{% block body %}
 <!--Gallery Section-->
    <section class="gallery-section fullwidth">

        <!--Mixituo Gallery-->
        <div class="mixitup-gallery">
            <!--Filter-->
            <div class="filters text-center">
            <div class="icon-box"><span class="fa fa-picture-o"></span></div>

                <ul class="filter-tabs filter-btns clearfix">
                    <li class="active filter" data-role="button" data-filter="all">All Projects</li>
                    {% for cls in classify %}
                    <li class="filter" data-role="button" data-filter=".{{ cls.classify.lower }}">{{ cls.classify }}</li>
                    {% endfor %}
                </ul>
            </div>


            <div class="filter-list clearfix">
                {% for img in wpics %}

                <!--Default Portfolio Item-->
                <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 default-portfolio-item mix mix_all all {{ img.fyr.classify.lower }}">
                    <div class="inner-box">
                        <figure class="image-box"><img src="/static/media/{{ img.fullpic }}" alt=""></figure>
                        <!--Overlay Box-->
                        <div class="overlay-one">
                            <div class="overlay-inner">
                                <div class="content">
                                    <a href="{% url 'furnitureapp:singletwo' 2 img.id %}" class="proj-link"><span class="fa fa-link"></span></a>
                                </div>
                            </div>
                        </div>
                        <!--Caption Box-->
                        <div class="caption-box-one">
                            <h3><a href="{% url 'furnitureapp:singletwo' 2 img.id %}">Wooden Sofa</a></h3>
                            <div class="cat-links"><a href="#">Furniture</a> , <a href="#">Lighting</a></div>
                        </div>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div><!--End Mixituo Gallery-->

        <div class="text-center padd-top-70"><a class="theme-btn btn-style-two" href="portfolio-standard.html">Load More</a></div>

    </section>
{% endblock %}
{% block link %}
<script src="/static/js/jquery.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<script src="/static/js/jquery.mCustomScrollbar.concat.min.js"></script>
<script src="/static/js/jquery.fancybox.pack.js"></script>
<script src="/static/js/jquery.fancybox-media.js"></script>
<script src="/static/js/owl.js"></script>
<script src="/static/js/mixitup.js"></script>
<script src="/static/js/wow.js"></script>
<script src="/static/js/script.js"></script>
{% endblock %}

templates/furnitureapp/portfolio-single-one.html
{% extends 'furnitureapp/base.html' %}
{% block page %}Wooden Sofa{% endblock %}
{% block middle %}Project Single 01{% endblock %}
{% block body %}
 <!--Project Details Section-->
    <section class="project-details">
    	<div class="auto-container">

            <!--Project Images-->
            <div class="project-images">
            	<div class="row clearfix">
                	<!--Image Column-->
                    {% for img in furnitureimg %}
                        {% if img.index == 1 %}
                    <div class="image-column col-lg-8 col-md-12 col-sm-12 col-xs-12">
                    	<figure class="image-box"><a href="/static/media/{{ img.furimg.name }}" class="lightbox-image" title="Image Caption Here"><img src="/static/media/{{ img.furimg.name }}" alt=""></a></figure>
                    </div>
                    <!--Image Column-->
                        {% elif img.index == 2 %}
                    <div class="image-column col-lg-4 col-md-4 col-sm-6 col-xs-12">
                    	<figure class="image-box"><a href="/static/media/{{ img.furimg.name }}" class="lightbox-image" title="Image Caption Here"><img src="/static/media/{{ img.furimg.name }}" alt=""></a></figure>
                    </div>
                        {% else %}

                    <!--Image Column-->
                    <div class="image-column col-md-4 col-sm-6 col-xs-12">
                    	<figure class="image-box"><a href="/static/media/{{ img.furimg.name }}" class="lightbox-image" title="Image Caption Here"><img src="/static/media/{{ img.furimg.name }}" alt=""></a></figure>
                    </div>
                        {% endif %}

                    <!--Image Column-->

                    {% endfor %}

                </div>
            </div>

            <!--Project Content-->
            {% for tit in furnitureInfo %}
            <div class="project-content">
            	<h2>{{ tit.title }}</h2>
            	<div class="row clearfix">
                	<!--Content Column-->
                    <div class="content-column col-lg-9 col-md-8 col-sm-12 col-xs-12">
                    	<div class="text">{{ tit.descirbe }}</div>
                        <div class="social-links">
                        	<a href="#"><span class="fa fa-facebook-f"></span></a>
                            <a href="#"><span class="fa fa-twitter"></span></a>
                            <a href="#"><span class="fa fa-dribbble"></span></a>
                            <a href="#"><span class="fa fa-google-plus"></span></a>
                            <a href="#"><span class="fa fa-skype"></span></a>
                        </div>
                    </div>

                    <!--Info Column-->
                    <div class="info-column col-lg-3 col-md-4 col-sm-12 col-xs-12">
                    	<ul class="proj-info">
                        	<li><strong>Category :</strong>  {{ tit.tag }}</li>
                            <li><strong>Client :</strong>  {{ tit.author }}</li>
                            <li><strong>Date :</strong>  {{ tit.pub_date|date:'d m,Y' }}</li>
                            <li><strong>Link :</strong>  {{ tit.tagweb }}</li>
                            <li class="rating"><strong>Rating :</strong>  <span class="fa fa-star"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span> <span class="fa fa-star-half-empty"></span> </li>
                        </ul>
                    </div>
                </div>
            </div>
            {% endfor %}

            <!-- Post Nav -->
            <div class="post-nav clearfix">
            	<a href="#" class="prev-post pull-left"><span class="fa fa-angle-left"></span> &ensp;&ensp;Previous Post</a>
                <a href="#" class="next-post pull-right">Next Post &ensp;&ensp;<span class="fa fa-angle-right"></span></a>
                <a href="{% url 'furnitureapp:portfoli' %}" class="all-post"><span class="fa fa-th-list"></span></a>
            </div>

        </div>
    </section>

{% endblock %}